#!/usr/bin/sh

create_user="CREATE USER IF NOT EXISTS 'holberton_user'@'localhost' IDENTIFIED WITH mysql_native_password BY 'projectcorrection280hbtn';"
grant_opt="GRANT CREATE, ALTER, DROP, INSERT, UPDATE, INDEX, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'holberton_user'@'localhost' WITH GRANT OPTION;"
grant_repl="GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost';"
flush="FLUSH PRIVILEGES;"

cat_command="${create_user}\n${grant_opt}\n${grant_repl}"

echo "$cat_command" | sudo mysql
