#!/usr/bin/env bash
# This script creates a file, infinitely displays and trap signals

rm_exit()
{
	rm /var/run/myscript.pid
	exit
}

trap "echo 'I hate the kill command' && rm_exit" TERM
trap "echo 'Y U no love me?!'" INT
trap "rm_exit" QUIT

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done
