#!/usr/bin/env bash
# A bash script that displays ``Best school`` 10 times,
# but for the 9th iteration also displays ``Hi`` on a new line

i=1

while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
