#!/usr/bin/env bash
# A bash script that displays the content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

dir_cont=$(ls)

for content in $dir_cont
do
	echo "$content" | cut -d '-' -f2
done
